In [50]:
import pandas as pd
import numpy as np
import random

In [51]:
df = pd.read_csv("fruit_data_with_colors.txt", delimiter = '\t')

In [52]:
df.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [53]:
df = df.drop(columns = ['fruit_label','fruit_name','fruit_subtype'], axis = 1)

In [54]:
df.head()

mass  width  height  color_score
0   192    8.4     7.3         0.55
1   180    8.0     6.8         0.59
2   176    7.4     7.2         0.60
3    86    6.2     4.7         0.80
4    84    6.0     4.6         0.79

In [55]:
x = np.array(df)
random.shuffle(x)
k = 4    

In [56]:
centroids_index = np.random.randint(0, 58,( 4,))
centroids_index

array([ 4, 20, 45, 52])

In [57]:
x[centroids_index]

array([[ 86.  ,   6.2 ,   4.7 ,   0.8 ],
       [178.  ,   7.1 ,   7.8 ,   0.92],
       [166.  ,   6.9 ,   7.3 ,   0.93],
       [172.  ,   7.1 ,   7.6 ,   0.92]])

In [58]:
ctds = x[centroids_index]

In [59]:
ctds

array([[ 86.  ,   6.2 ,   4.7 ,   0.8 ],
       [178.  ,   7.1 ,   7.8 ,   0.92],
       [166.  ,   6.9 ,   7.3 ,   0.93],
       [172.  ,   7.1 ,   7.6 ,   0.92]])

In [60]:
x= np.delete(x,centroids_index, axis = 0)

In [61]:
clusters = [[], [], [], []]
clusters[0].append(ctds[0])
clusters[1].append(ctds[1])
clusters[2].append(ctds[2])
clusters[3].append(ctds[3])

In [62]:
def euclidean_distance(centroid, x):
    difference = np.array(x) - np.array(centroid)
    sqrd_diff = np.square(difference)
    sum_sqrd_diff = np.sum(sqrd_diff, axis = 1)
    distance = np.sqrt(sum_sqrd_diff)
    
    return distance

In [63]:
clusters

[[array([86. ,  6.2,  4.7,  0.8])],
 [array([178.  ,   7.1 ,   7.8 ,   0.92])],
 [array([166.  ,   6.9 ,   7.3 ,   0.93])],
 [array([172.  ,   7.1 ,   7.6 ,   0.92])]]

In [64]:
len(clusters[0])

1

In [65]:
len(clusters[1])

1

In [66]:
len(clusters[2])

1

In [67]:
len(clusters[3])

1

In [68]:
c1 = euclidean_distance(ctds[0], x)
c2 = euclidean_distance(ctds[1], x)
c3 = euclidean_distance(ctds[2], x)
c4 = euclidean_distance(ctds[3], x)

In [69]:
c1

array([1.06054998e+02, 9.40409172e+01, 9.00429342e+01, 0.00000000e+00,
       1.06054998e+02, 0.00000000e+00, 1.00324523e+01, 9.20566912e+01,
       1.00324523e+01, 6.02668234e+00, 8.60391661e+01, 9.20566912e+01,
       6.02080559e+00, 8.60536716e+01, 1.00324523e+01, 6.80470896e+01,
       6.02668234e+00, 1.06054998e+02, 9.20566912e+01, 7.60490033e+01,
       8.60536716e+01, 0.00000000e+00, 2.01248602e+00, 9.14005370e+02,
       8.40726257e+01, 6.80470896e+01, 6.02080559e+00, 1.06054998e+02,
       9.40409172e+01, 8.00454052e+01, 9.20566912e+01, 7.20600451e+01,
       1.00324523e+01, 1.00324523e+01, 2.01248602e+00, 8.60536716e+01,
       7.20600451e+01, 6.02668234e+00, 2.99140001e+04, 1.06054998e+02,
       7.60490033e+01, 7.60505917e+01, 7.80403101e+01, 1.24054224e+02,
       7.00623408e+01, 1.08149757e+02, 2.01248602e+00, 6.60661192e+01,
       2.99140001e+04, 7.20600451e+01, 1.24054224e+02, 6.02668234e+00,
       8.00454052e+01, 7.40643882e+01, 1.00106226e+02])

In [70]:
ctds[0]

array([86. ,  6.2,  4.7,  0.8])

In [71]:
len(x)

55

In [72]:
len(c1)

55

In [73]:
for i in x:
    id = np.argmin(euclidean_distance(i, ctds))
    clusters[id].append(i)

In [74]:
clusters

[[array([86. ,  6.2,  4.7,  0.8]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([80.  ,  5.9 ,  4.3 ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.9 ,  4.3 ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.8 ,  4.3 ,  0.77])],
 [array([178.  ,   7.1 ,   7.8 ,   0.92]),
  array([192.  ,   8.4 ,   7.3 ,   0.55]),
  array([180.  ,   8.  ,   6.8 ,   0.59]),
  array([176. ,   7.4,   7.2,   0.6]),
  array([192.  ,   8.4 ,   7.3 ,   0.55]),
  array([178.  ,   7.1 ,   7.8 ,   0.92]),
  array([178.  ,   7.1 ,   7.8 ,   0.92]),
  array([192.  ,

In [75]:
ctds[0] = np.mean(clusters[0], axis = 0)
ctds[1] = np.mean(clusters[1], axis = 0)
ctds[2] = np.mean(clusters[2], axis = 0)
ctds[3] = np.mean(clusters[3], axis = 0)

In [90]:
for i in range(1):
    prev_clusters = clusters
    
    prev_centroids = [ctds[0], ctds[1], ctds[2], ctds[3]]
    c1 = euclidean_distance(ctds[0], x)
    c2 = euclidean_distance(ctds[1], x)
    c3 = euclidean_distance(ctds[2], x)
    c4 = euclidean_distance(ctds[3], x)
    
    clusters = [[], [], [], []]
    clusters[0].append(ctds[0])
    clusters[1].append(ctds[1])
    clusters[2].append(ctds[2])
    clusters[3].append(ctds[3])
    
    for j in x:

        id = np.argmin(euclidean_distance(j, ctds))
        clusters[id].append(j)
    
    ctds[0] = np.mean(clusters[0], axis = 0)
    ctds[1] = np.mean(clusters[1], axis = 0)
    ctds[2] = np.mean(clusters[2], axis = 0)
    ctds[3] = np.mean(clusters[3], axis = 0)
    
    new_centroids = [ctds[0], ctds[1], ctds[2], ctds[3]]
    
    if np.array_equiv( prev_centroids, new_centroids):
        print("Centroids of newly formed clusters do not change.")
        break
    
    if np.array_equiv(prev_clusters, clusters):
        print("Points remain in the same cluster.")
        break
        
    
clusters

Centroids of newly formed clusters do not change.


[[array([80.58823816,  5.91764721,  4.33529431,  0.79529412]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([80.  ,  5.9 ,  4.3 ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([86. ,  6.2,  4.7,  0.8]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.9 ,  4.3 ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([76.  ,  5.8 ,  4.  ,  0.81]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.8 ,  4.3 ,  0.77]),
  array([84.  ,  6.  ,  4.6 ,  0.79]),
  array([80.  ,  5.8 ,  4.3 ,  0.77])],
 [array([2.96692506e+04, 7.10660494e+00, 7.50265432e+00, 7.79271605e-01]),
  array([3.0e+04, 7.1e+00, 7.5e+00, 7.8e-01]),
  array([3.0e+04, 7.1e+00, 7.5e+00, 7.8e-01])],
 [array([174.22317161,   7.46556926,   7.53135128,   0.78546244]),
  array([192.  ,   8.4 ,   7.3 ,   0.55]),
  arr

In [78]:
len(clusters[0])

18

In [79]:
len(clusters[1])

3

In [80]:
len(clusters[2])

13

In [81]:
len(clusters[3])

25

In [94]:
total = len(clusters[0]) + len(clusters[1]) + len(clusters[2]) + len(clusters[3])
total

59